% Finds returns indices that break down which layer each fragment is from.
% 
% @INPUTS
%   FragData: struct containing information about fragments including
%       attenuation measurements. This struct is generated by
%       generateSharedData.m
% 
% @OUTPUTS
%   ot: idx corresponding to fragments from the outer table
%   med: idx corresponding to fragments from the medullary
%   it: idx corresponding to fragmens from the inner table
%   unknown: idx corresponding to fragments without a clear source
% 
% Taylor Webb
% Summer 2019

function [ot,med,it,unknown] = fragmentLayers(FragData)

% Since I don't know how many fragmens are from each layer, ignore the
% error about an array growing through a loop
%#ok<*AGROW>

ot = [];
med = [];
it = [];
unknown = [];
for ii = 1:length(FragData)
    if strcmp(FragData(ii).Layer,'Outer Table')
        ot(end+1) = ii;
    elseif strcmp(FragData(ii).Layer,'Trabecular')
        med(end+1) = ii;
    elseif strcmp(FragData(ii).Layer,'Inner Table')
        it(end+1) = ii;
    elseif strcmp(FragData(ii).Layer,'Unknown')
        unknown(end+1) = ii; 
    else
        error(['Unknown layer type: ', FragData(ii).Layer]);
    end
end