function [a,b,gof] = myNonlinearFit(x,y)
%CREATEFIT(ALPHA,F)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : alpha
%      Y Output: f
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 09-Sep-2019 09:16:00


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData(x, y);

% Set up fittype and options.
ft = fittype( 'power1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
% opts.Lower = [2.49 -Inf];
% opts.StartPoint = [3.33647011232401 2.49];
% opts.Upper = [2.49 Inf];
% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'Fit' );
% h = plot( fitresult, xData, yData );
% legend( h, 'Data', 'Fit', 'Location', 'NorthEast' );
% % Label axes
% xlabel x
% ylabel y
% grid on

a = fitresult.a;
b = fitresult.b;

